name: Release and Deploy

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - run: apt-get update -y && apt-get install -y git unzip

      - uses: https://code.forgejo.org/actions/checkout@v4

      - uses: https://code.forgejo.org/actions/setup-node@v4
        with:
          deno-version: v22.x

      - run: |
          npm ci
          npm run build

      - name: Upload Pages Artifact
        uses: https://code.forgejo.org/forgejo/upload-artifact@v4
        with:
          path: "dist/"

  release:
    needs: "build"

    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: "Release"
        id: "release"
        uses: "https://github.com/googleapis/release-please-action@v4"

      - name: Create tarball
        if: ${{ steps.release.outputs.release_created }}
        run: tar czf catppuccin-gitea.tar.gz --directory=./dist .

      - name: Upload Release Artifacts
        if: ${{ steps.release.outputs.release_created }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh release upload ${{ steps.release.outputs.tag_name }} ./catppuccin-gitea.tar.gz


  deploy:
    needs: "build"

    runs-on: "ubuntu-latest"

    permissions:
      pages: "write"
      id-token: "write"

    environment:
      name: "github-pages"
      url: "${{ steps.deployment.outputs.page_url }}"

    steps:
      - name: "Deploy to GitHub Pages"
        id: "deployment"
        uses: "actions/deploy-pages@v4"
